import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import React from "react";
import { 
  Simulation,
  createSimulation,
  initializeSimulation,

 } from "@/lib/fluid/Simulation";
import { FluidApp, webGLStart } from "@/lib/fluid/app";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next.js Fluid Simulation App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  const handleOnLoad = () => {
    try {
      if(!webGLStart()) {
        throw new Error('Failed to start WebGL');
      }
    } catch (error) {
      console.error(error);
    }
  };

  return (
    <html lang="en">
      <body className={inter.className} onLoad={handleOnLoad}>{children}</body>
    </html>
  );
}
